apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-prediction
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shilu10/weather_prediction.git
    targetRevision: HEAD
    path: deployment/deployment_manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true